- .changeset/flat-moose-complain.md
- packages/annotation-converter/package.json
- packages/edmx-parser/package.json
- packages/vocabularies-types/package.json
Following some code move the npm package was not viable anymore.
This PR fixes that
> feat: adjust the package content for the vocabularies-types

- .husky/pre-commit
- packages/annotation-converter/package.json
- packages/edmx-parser/package.json
- packages/vocabularies-types/package.json
With this commit I add some general info on the pacakge that will be visible in the next publish on npm
> chore: add repository info and bugs for the package

- .changeset/shy-walls-destroy.md
- packages/annotation-converter/src/converter.ts
Missed the case where we just push
> fix: annotation source definition in all cases

- .changeset/silly-falcons-count.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/annotation-converter/test/fixtures/v4/AnnoNoContainment.xml
- packages/annotation-converter/test/fixtures/v4/AnnoWithContainment.xml
- packages/vocabularies-types/src/Edm.ts
> fix: make sure all entity types have an 'annotations' property

- .changeset/empty-rats-design.md
- packages/fe-mockserver-core/package.json
- pnpm-lock.yaml
I am not sure if the `@types/...` packages are really missing or if the intention was to use a completely different package.
> chore: add missing types

- .changeset/curly-ravens-travel.md
- packages/fe-mockserver-core/package.json
- pnpm-lock.yaml
Just realized this is not ok so far :/
> fix: dependencies were not correctly defined

- .changeset/heavy-foxes-switch.md
- packages/fe-mockserver-core/src/api.ts
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/index.ts
- packages/fe-mockserver-plugin-cds/test/__snapshots__/index.spec.ts.snap
- packages/fe-mockserver-plugin-cds/test/cds/valid-withmorecommon.cds
- packages/fe-mockserver-plugin-cds/test/index.spec.ts
- packages/ui5-middleware-fe-mockserver/src/configResolver.ts
- packages/ui5-middleware-fe-mockserver/test/configResolver.test.ts
Currently the generateMockData parameter was ignored :D
> fix: mockdata generation now works as intended

- .changeset/khaki-zoos-push.md
- packages/fe-mockserver-core/src/middleware.ts
- packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap
- packages/fe-mockserver-core/test/unit/__testData/RootElement.json
- packages/fe-mockserver-core/test/unit/middleware.test.ts
- packages/ui5-middleware-fe-mockserver/README.md
The urlPath for annotation file can now contains '*' character.
> fix: annotation local path

- .changeset/giant-hotels-relate.md
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/v2/__snapshots__/dataAccess.test.ts.snap
- packages/fe-mockserver-core/test/unit/v2/dataAccess.test.ts
- packages/fe-mockserver-core/test/unit/v4/__snapshots__/weirdKeys.test.ts.snap
- packages/fe-mockserver-core/test/unit/v4/services/weirdKeys/A.json
- packages/fe-mockserver-core/test/unit/v4/services/weirdKeys/service.cds
- packages/fe-mockserver-core/test/unit/v4/weirdKeys.test.ts
Boolean keys were evaluated as string which obviously is wrong :)
> fix: boolean keys are now working correctly

- .changeset/tasty-balloons-happen.md
- packages/annotation-converter/src/converter.ts
This leads to runtime exception in some case while accessing annotations
> fix: apparently null is a typeof object !

- .changeset/stale-hats-boil.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/edmx-parser/src/utils.ts
- packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap
They were simply ignored up until now :D
> fix: Singleton are properly resolved

- .changeset/loud-years-clean.md
- packages/edmx-parser/src/parser.ts
- packages/vocabularies-types/src/Edm.ts
Currently this only considered singleton to singleton and entityset to entityset.
Now we support cross referencing :)
> feat: support navigation property binding for singleton

- .changeset/green-wolves-share.md
- packages/fe-mockserver-core/src/data/entitySets/stickyEntitySet.ts
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap
Currently only undefined was triggering that logic
> fix: 404 on null data

- .changeset/tasty-planets-learn.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
Some keys were not handled and resulted in 404 because of that
> fix: decode uri component

- .changeset/wild-rules-explode.md
- packages/fe-mockserver-plugin-cds/package.json
- pnpm-lock.yaml
This gets outdated too quickly with exact versions
> chore: Relax the range of supported CDS compiler versions

- .changeset/tender-rabbits-watch.md
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/src/request/filterParser.ts
- packages/fe-mockserver-core/test/unit/request/__snapshots__/filterParser.test.ts.snap
- packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
- packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
Added functionality to support new feature request: https://github.com/SAP/open-ux-odata/issues/253
Follow up based on @joe-skrzypczak-fioneer code
> Support nested functions in filter

- .changeset/forty-panthers-remain.md
- docs/DefiningMockdata.md
- docs/EntityContainerAPI.md
- docs/MockserverAPI.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/mockdata/mockEntityContainer.ts
- packages/fe-mockserver-core/test/unit/v2/__snapshots__/functionImport.test.ts.snap
- packages/fe-mockserver-core/test/unit/v2/functionImport.test.ts
- packages/fe-mockserver-core/test/unit/v2/services/FunctionImport/metadata.xml
- packages/fe-mockserver-core/test/unit/v4/__snapshots__/unboundAction.test.ts.snap
- packages/fe-mockserver-core/test/unit/v4/services/unboundAction/EntityContainer.js
- packages/fe-mockserver-core/test/unit/v4/services/unboundAction/RootEntity.json
- packages/fe-mockserver-core/test/unit/v4/services/unboundAction/service.cds
- packages/fe-mockserver-core/test/unit/v4/unboundAction.test.ts
- packages/ui5-middleware-fe-mockserver/README.md
- We now support getEntityInterface on the base API for the EntityContainer.js
- Slightly improved the documentation to be more helpful hopefully :)
> feat: add one base method to the EntityContainer extension

- .changeset/fast-candles-breathe.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/types.d.ts
data access used to keep logging debugging messages even if debug was turned off
> feat: reduce log messages if debug=false

- .changeset/dirty-melons-attend.md
Been a while since this was released :)
> feat: upgrade vocabularies types

- .changeset/perfect-lamps-pull.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/v4/__snapshots__/weirdKeys.test.ts.snap
- packages/fe-mockserver-core/test/unit/v4/services/weirdKeys/A.json
- packages/fe-mockserver-core/test/unit/v4/weirdKeys.test.ts
By decoding the keys value a little bit later we avoid this problem
> fix: slash based keys

- .changeset/two-candles-grow.md
- packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts
- packages/fe-mockserver-core/src/logger.ts
- packages/vocabularies-types/utils/generate_types.ts
- samples/function-import/package.json
- samples/function-import/webapp/Component.js
- samples/function-import/webapp/manifest.json
- improve the logging
- fix one sample :)
> fix: draft choreography is slightly better

- .changeset/swift-socks-judge.md
- packages/annotation-converter/src/writeback.ts
- packages/annotation-converter/test/writeback.spec.ts
- packages/edmx-parser/src/parser.ts
- packages/edmx-parser/test/fixtures/v2/metadata_analytics.xml
- packages/vocabularies-types/src/BaseEdm.ts
#287 
1. Added FloatExpression type in vocabularies-types
2. support for parsing Float inline expression
3. Support converting Int, Float, Date and Boolean object to raw type
> feat: support reverting primitive type object to its raw type

- .changeset/sixty-rivers-brush.md
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/fe-mockserver-core/test/unit/v4/__snapshots__/dataAccess.test.ts.snap
- packages/fe-mockserver-core/test/unit/v4/services/complexType/A.json
- packages/fe-mockserver-core/test/unit/v4/services/complexType/complexType.cds
- packages/fe-mockserver-core/test/unit/v4/services/complexType/metadata.xml
Currently we stopped only at the first level, which created issues in some case :)
> fix: nested complex type are now checked for nullability

- .changeset/many-pans-sparkle.md
- .github/workflows/lockfiles-command.yml
- .github/workflows/pipeline.yml
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
Instead of checking A exists withing B it was testing the otherway around leading to incorrect results.
> fix: substringof filter was applied incorrectly

- .changeset/afraid-icons-sort.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/annotation-converter/test/fixtures/v4/ComplexType.xml
- packages/annotation-converter/test/fixtures/v4/PVinline.xml
Fix for #357 
The types should at least no longer be incorrect :) They may not be completely resolved though
> fix: Inferred types for sub record are more accurately resolved

- .changeset/nervous-panthers-notice.md
- packages/fe-mockserver-core/src/middleware.ts
- packages/fe-mockserver-core/src/router/serviceRouter.ts
Currently it could happen that this also impacted other resources...
> fix: make sure the disable cache header is only applied to the mockserver

- .changeset/small-tomatoes-share.md
- packages/ui5-middleware-fe-mockserver/src/index.ts
- pnpm-lock.yaml
- samples/basic-usage/package.json
While not ideal code wise this should solve #409 and maintain compatibility with older tooling version
> feat: Add support for ui5 tooling 3.x

- .changeset/calm-crews-burn.md
- packages/fe-mockserver-core/src/data/metadata.ts
- packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
- packages/vocabularies-types/utils/generate_types.ts
After discussing with @BerSie we came to the conclusion that while this is not really recommended it should still be feasible so here we go.
> feat: allow action to be resolved despite namespace

- .changeset/young-lobsters-ring.md
- docs/MockserverAPI.md
- packages/fe-mockserver-core/src/data/common.ts
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts
- packages/fe-mockserver-core/test/unit/v4/__snapshots__/multiLevelExpand.test.ts.snap
- packages/fe-mockserver-core/test/unit/v4/multiLevelExpand.test.ts
- packages/fe-mockserver-core/test/unit/v4/parametrizedDataAccess.test.ts
- packages/fe-mockserver-core/test/unit/v4/services/multiLevelExpand/A.js
- packages/fe-mockserver-core/test/unit/v4/services/multiLevelExpand/A.json
- packages/fe-mockserver-core/test/unit/v4/services/multiLevelExpand/B.json
- packages/fe-mockserver-core/test/unit/v4/services/multiLevelExpand/service.cds
New API in the mockdataContributor to specify which source and target property should be compared
> feat: allow custom referential constraints to be defined

- .changeset/beige-jeans-invent.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/vocabularies-types/src/Edm.ts
Currently we cannot access a root level entity type without an entity set, this PR changes that :)
> feat: allow to resolve entity type by their fqdn

- .changeset/pink-feet-hammer.md
- packages/fe-mockserver-core/src/request/applyParser.ts
- packages/fe-mockserver-core/src/request/commonTokens.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
This is far from perfect but should at least cover what we had working before my hierarchies change :)
> fix: complex aggregate queries are now working again

- .changeset/cold-turkeys-sell.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
Contains a unit test illustrating issue #494
> Issue with search and DrillState

- .changeset/yellow-humans-compare.md
- packages/fe-mockserver-core/src/request/applyParser.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
> We now support groupBy apply expression on navigation expressions

- .changeset/short-trains-end.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
> fix: group by query may not have aggregate defined

- .changeset/loud-wolves-hope.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/annotation-converter/test/fixtures/v2/metadataWithApply.xml
- packages/annotation-converter/test/fixtures/v4/metamodelEnums.xml
- packages/edmx-parser/src/utils.ts
- packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap
See http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406397932
Fixes #593
> fix: references must be unique

- .changeset/giant-zoos-build.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
> fix: complex expand are now working correctly in v2

- .changeset/slow-pots-press.md
- packages/fe-mockserver-core/package.json
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
- pnpm-lock.yaml
Follow up on the nested expand fix
> fix: deep merge for nested expand

- .changeset/great-dolls-try.md
- packages/fe-mockserver-core/src/request/filterParser.ts
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
> feat: add a bit more logging in debug

- .changeset/young-maps-cry.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/test/unit/__testData/RootElement.json
- packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
- packages/fe-mockserver-core/test/unit/v4/services/formSample/FormTemplate.cds
Internal incident and manual test revealed that the draft admin data was not maintained properly
As it happens we were not updating the source info properly
> fix: make sure draft admin data is updated properly

- .changeset/five-squids-mate.md
- packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts
- packages/fe-mockserver-core/test/unit/data/functionBasedMockData.test.ts
- packages/fe-mockserver-core/test/unit/data/mockdata/MyRootEntity.js
Internal testing revealed this nice error
> fix: tenant based mock data will no longer leak onto one another

- .changeset/cyan-balloons-build.md
- packages/vocabularies-types/src/Edm.ts
- packages/vocabularies-types/utils/generate_types.ts
Required for proper typing in sap.fe
> fix: update dynamic types list

- .changeset/sour-waves-check.md
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
The issue is not fully fixed, but I've added a corresponding unit test.
> fix: cannot create a node in a hierarchy and a node below it

- .changeset/twenty-boats-lie.md
- packages/fe-mockserver-core/src/request/commonTokens.ts
- packages/fe-mockserver-core/test/unit/v4/parametrizedDataAccess.test.ts
Fix for #676 
The tokens are now more lenient and should allow for longer alternatives
> fix: prevent keyword from interfering with queries

- .changeset/many-rules-travel.md
- packages/vocabularies-types/src/Edm.ts
- packages/vocabularies-types/utils/generate_types.ts
> fix: adjust build following vocabularies change

- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/src/request/commonTokens.ts
- packages/fe-mockserver-core/src/request/filterParser.ts
- packages/fe-mockserver-core/test/unit/request/__snapshots__/filterParser.test.ts.snap
- packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
- packages/fe-mockserver-core/test/unit/v2/dataAccess.test.ts
- packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
> fix: `not` operator is now supported in filters

- .changeset/sour-keys-doubt.md
- packages/fe-mockserver-core/src/data/entitySets/stickyEntitySet.ts
- packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
...otherwise one cannot update a new object
> fix: data is now fetched from the session if one exists

- .changeset/little-ducks-sleep.md
- packages/fe-mockserver-core/src/request/commonTokens.ts
- packages/fe-mockserver-core/test/unit/request/__snapshots__/filterParser.test.ts.snap
- packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
> fix: datetimeoffset are now properly parsed

- .changeset/cyan-brooms-greet.md
- packages/edmx-parser/src/parser.ts
- packages/vocabularies-types/src/BaseEdm.ts
Currently the expected type was just string[] which resulted in some non nice coding elsewhere
> fix: improve the collection type

- .changeset/long-clouds-rhyme.md
- packages/vocabularies-types/src/BaseEdm.ts
Small update to improve the typing used in sap.fe
This is mostly around the RawAnnotation type
> fix: make the types better

- .changeset/eight-chicken-itch.md
- packages/vocabularies-types/utils/generate_types.ts
> fix: revert previous change

- .changeset/sweet-knives-complain.md
- packages/fe-mockserver-core/src/router/batchRouter.ts
> fix: remove an extra CRLF in batch response

- .changeset/silly-dogs-glow.md
- packages/fe-mockserver-core/src/router/catalogServiceRouter.ts
- packages/fe-mockserver-core/src/router/serviceRouter.ts
- packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap
- packages/fe-mockserver-core/test/unit/__testData/Requestor.ts
- packages/fe-mockserver-core/test/unit/middleware.test.ts
Fix for #820 
We now properly create the service document for v2 and v4 services
> feat: we now properly support root service document

- .changeset/ten-bags-sin.md
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/test/unit/data/entitySet.test.ts
The code was always expecting an expression.
Fixes internal issue 247
> fix: we now allow empty lambda operations

- .changeset/smooth-islands-approve.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/test/unit/request/__snapshots__/odataRequest.test.ts.snap
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
Further fix for internal issue
> fix: lambda are now properly parsed in expand

- .changeset/cold-files-argue.md
- packages/fe-mockserver-core/package.json
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- pnpm-lock.yaml
We create more index as long as we `can` index the data :) (no duplicates)
> Slightly improved version of the index generation

- .changeset/short-rocks-rest.md
To include https://github.com/SAP/odata-vocabularies/pull/325
> feat: update vocabulary

- .changeset/hip-berries-greet.md
- package.json
- packages/annotation-converter/src/writeback.ts
- packages/edmx-parser/src/parser.ts
- packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap
- packages/edmx-parser/test/__snapshots__/parser.spec.ts.snap
- packages/edmx-parser/test/fixtures/v4/edmJson.metadata.xml
- packages/edmx-parser/test/parser.spec.ts
- packages/edmx-parser/utils/edmx.d.ts
- packages/vocabularies-types/src/BaseEdm.ts
- packages/vocabularies-types/src/Edm.ts
Some known issue around ordering of mixed element set that would be too annoying to fix right now are also known :)
> feat: we now properly parse complex and nested expressions

- .changeset/purple-beers-visit.md
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/fe-mockserver-core/test/unit/v4/hierarchyDraftAccess.test.ts
- packages/fe-mockserver-core/test/unit/v4/services/hierarchy/draftService.cds
A hierarchy of sub-objects within a draft instance was not computed correctly
> fix: Correct hierarchy of subobjects within a draft

- .changeset/neat-spoons-do.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/router/batchRouter.ts
- packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap
- packages/fe-mockserver-core/test/unit/middleware.test.ts
The ETag info was not yet pushed to the patch and post result
> feat: etag on patch

- .changeset/lazy-hats-clap.md
- packages/annotation-converter/test/fixtures/v4/boundActionOverload.xml
- packages/annotation-converter/test/fixtures/v4/v4Meta.xml
- packages/edmx-parser/src/parser.ts
- packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap
- packages/edmx-parser/test/__snapshots__/parser.spec.ts.snap
Fixing $Path Handing
Some refactoring introduced a change in the naming which i forgot to revert.
> fix: Fix for #862

- .changeset/flat-months-joke.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/src/utils.ts
- packages/annotation-converter/src/writeback.ts
- packages/edmx-parser/src/parser.ts
- packages/edmx-parser/utils/edmx.d.ts
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/vocabularies-types/src/BaseEdm.ts
- packages/vocabularies-types/src/Edm.ts
Fix for https://github.com/SAP/open-ux-odata/issues/840
> Improve support for Edm.Double

- .changeset/nice-falcons-count.md
- packages/fe-mockserver-core/src/data/entitySets/entitySet.ts
Add a bit of logging when mockdata are missing
> fix: log missing mockdata

- .changeset/angry-poets-impress.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/test/unit/v2/dataAccess.test.ts
- packages/fe-mockserver-core/test/unit/v2/services/productSample/SEPMRA_C_PD_Product.json
Fix for https://github.com/SAP/open-ux-odata/issues/851
> fix: order by should respect the ordering with respect to nullable properties

- .changeset/big-houses-dress.md
- .github/workflows/pipeline.yml
- packages/fe-mockserver-core/babellogger.config.js
- packages/fe-mockserver-core/jest.config.js
- packages/fe-mockserver-core/package.json
- packages/fe-mockserver-core/src/api.ts
- packages/fe-mockserver-core/src/data/dataAccess.ts
- packages/fe-mockserver-core/src/middleware.ts
- packages/fe-mockserver-core/src/router/serviceRouter.ts
- packages/ui5-middleware-fe-mockserver/README.md
- packages/ui5-middleware-fe-mockserver/babellogger.config.js
- packages/ui5-middleware-fe-mockserver/jest.config.js
- packages/ui5-middleware-fe-mockserver/package.json
- packages/ui5-middleware-fe-mockserver/src/configResolver.ts
- packages/ui5-middleware-fe-mockserver/src/index.ts
- packages/ui5-middleware-fe-mockserver/test/index.test.ts
- pnpm-lock.yaml
Also we no longer depend on deprecated ui5/logger @2
> feat: we now support defining your own logger

- .changeset/nervous-jokes-train.md
- packages/annotation-converter/src/writeback.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/annotation-converter/test/fixtures/v2/sideEffects.xml
Fix for #906 
EnumMember can be "Flags", which in turn mean that you can specify multiple values in the enum value.
In order to represent this properly, the converter introduce an array.
This array was not reverted properly :)
> fix: "Flag" enum are now properly converted back to single value instead of a collection

- .changeset/pink-eyes-grin.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/src/router/serviceRouter.ts
- packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
> feat: we now properly support x-http-method to pass more information

- .changeset/big-apes-peel.md
- packages/fe-mockserver-core/src/request/odataRequest.ts
- packages/fe-mockserver-core/src/router/batchRouter.ts
- packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap
- packages/fe-mockserver-core/test/unit/__testData/Requestor.ts
- packages/fe-mockserver-core/test/unit/middleware.test.ts
Fix #910 
It's basic but it works
> feat: veeeeeeeeery basic json batch support

- .changeset/nine-moons-vanish.md
- packages/annotation-converter/src/converter.ts
- packages/annotation-converter/test/converterTest.spec.ts
- packages/annotation-converter/test/fixtures/v4/with-alias.xml
> fix: we fixed an issue with aliased vocabularies

- .changeset/famous-hotels-cross.md
- packages/fe-mockserver-core/src/request/searchParser.ts
- packages/fe-mockserver-core/test/unit/request/searchParser.test.ts
> fix: we fixed an issue while searching for words containing OR / AND

- .changeset/shy-pants-suffer.md
- packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
- packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts
The type was no considering the case where a single value was returned
> fix: adjust the type for afterRead

- .changeset/fair-comics-shave.md
- packages/fe-mockserver-core/src/api.ts
- packages/fe-mockserver-core/src/data/serviceRegistry.ts
- packages/fe-mockserver-core/src/index.ts
- packages/fe-mockserver-core/src/router/serviceRouter.ts
- packages/ui5-middleware-fe-mockserver/src/configResolver.ts
Nothing much right now to see :)
> fix: introduce an experimental setting for capture

- .changeset/great-colts-cough.md
- packages/fe-mockserver-core/src/router/serviceRouter.ts
> fix: we now ignore the cache requested by the browser when capturing

- .changeset/neat-dancers-know.md
- packages/fe-mockserver-core/src/plugins/fileSystemLoader.ts
- packages/ui5-middleware-fe-mockserver/src/configResolver.ts
Let's not try to run ts-node :)
> fix: when CAP embeds ui5 which embeds the mockserver

- .changeset/tough-nails-jog.md
- packages/fe-mockserver-core/src/plugins/fileSystemLoader.ts
> fix: TS with CAP fixes

- .changeset/eleven-yaks-promise.md
- packages/fe-mockserver-core/src/data/dataAccess.ts
Action were setting the count under some circumstances, which is wrong
> fix: side effect of fetching the object
