.changeset/wise-items-laugh.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/merge/annotations.xml, packages/annotation-converter/test/fixtures/merge/metadata.xml, packages/annotation-converter/test/writeback.spec.ts, packages/edmx-parser/src/parser.ts, packages/edmx-parser/src/utils.ts, packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap, packages/edmx-parser/test/fixtures/merge/annotations.xml, packages/edmx-parser/test/fixtures/merge/metadata.xml, packages/edmx-parser/test/merge.spec.ts, packages/fe-mockserver-core/test/__snapshots__/middleware.test.ts.snap, packages/vocabularies-types/src/Edm.ts, packages/vocabularies-types/utils/generate_types.ts
Currently annotation of record or other annotations are always pulled from their node and brought back at the top of the service.
This doesn't work in case there are annotation overrides defined that would replace their source. We then end up with incoherent data.
=> fix: embedded annotation should not be taken to top level

.changeset/twelve-socks-sniff.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/pathError.xml
In case the Target resolved to a string the code was not considering this as an error
=> fix: incorrect annotation file format are now properly supported

.changeset/dull-birds-call.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.json, packages/fe-mockserver-core/test/unit/v4/__snapshots__/dataAccess.test.ts.snap, packages/fe-mockserver-core/test/unit/v4/__snapshots__/multiLevelExpand.test.ts.snap, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/complexType/A.json, packages/fe-mockserver-core/test/unit/v4/services/complexType/B.json, packages/fe-mockserver-core/test/unit/v4/services/complexType/complexType.cds, packages/fe-mockserver-core/test/unit/v4/services/complexType/metadata.xml
This fixes requests like `GET /Root?$expand=children($select=complexType/member)`, which returned empty data for all children before.
Also now always includes key properties in the response, even if they are not explicitly selected by the client. This aligns the behaviour with the CAP and ABAP implementations of the OData protocol.
=> fix: $select query option involving paths to complex type members now returns correct data

.changeset/neat-cats-rush.md, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/test/unit/data/data/MyEntityData.json, packages/fe-mockserver-core/test/unit/data/data/service.cds, packages/fe-mockserver-core/test/unit/data/entitySet.test.ts, packages/fe-mockserver-core/test/unit/request/__snapshots__/filterParser.test.ts.snap, packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
Add support for complex, nested lambda function such as `((ArrayData/any(t:t/SubArray/any(a0:a0/Name eq 'Something' and a0/SubSubArray/any(a1:a1/Value ge '20220600') and a0/SubSubArray/any(a1:a1/Value le '20220603'))))) and (BaseData eq 'FirstCheck')`
Fixed first the parser implementation to parse that flavor properly.
Then fixed the filter interpretator to properly deal with this.
=> feat: add support for complex lambda functions

.changeset/sour-points-rush.md, packages/fe-mockserver-core/src/data/common.ts, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/data/entitySets/stickyEntitySet.ts, packages/fe-mockserver-core/src/index.ts, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/data/entitySet.test.ts, packages/fe-mockserver-core/test/unit/data/functionBasedMockData.test.ts, packages/fe-mockserver-core/test/unit/data/mockdata/MyRootEntity.js, packages/fe-mockserver-core/test/unit/data/mockdata/MyRootEntity.json, packages/fe-mockserver-core/test/unit/data/mockdata/MySecondEntity.json, packages/fe-mockserver-core/test/unit/data/mockdata/service.cds, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/ui5-middleware-fe-mockserver/src/index.ts
Fixes #127 
- All the function based mockdata will now receive the request object that contains a lot of information, especially the tenantId
- Search and Filter can now be evaluated individually and overwritten
- sap messages can be added to any request manually
=> feat: improve the function based mockdata

.changeset/smart-guests-peel.md, packages/ui5-middleware-fe-mockserver/src/configResolver.ts, packages/ui5-middleware-fe-mockserver/test/configResolver.test.ts, packages/ui5-middleware-fe-mockserver/test/index.test.ts
This was supported a long time ago and since then we always check if there are data this can fail
=> fix: Default mockdata folder to the folder containing the metadata if missing

.changeset/seven-dolphins-relax.md, packages/vocabularies-types/.gitignore, packages/vocabularies-types/package.json, packages/vocabularies-types/tsconfig.json
Package size will increase but since it should always be a devDep and not used in targets apps this should be fine.
=> fix: Export the JS code for the enums for people not using TS

.changeset/modern-islands-join.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/vocabularies-types/src/Edm.ts, packages/vocabularies-types/utils/generate_types.ts
Currently the type often including a reference to a term property that may not exist.
Furthermore the terms when defined were just string instead of being the actual values making the switch case determination more complex than it could have been.
=> feat: Improve type definition

.changeset/spotty-terms-type.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/src/writeback.ts, packages/annotation-converter/test/converterTest.spec.ts
In some cases we ended up with a non existing annotations object which doesn't fit with the type definition
=> fix: make sure annotations object is defined as per the type def

.changeset/tiny-points-boil.md, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap, packages/edmx-parser/test/fixtures/v4/static-action.xml, packages/edmx-parser/test/parser.spec.ts, packages/vocabularies-types/src/Edm.ts
Add a new property `isCollection` to the `ActionParameter` type that indicates whether the parameter is collection-valued. This makes it easier to decide whether an action is "static".
=> feat: add flag for collection-valued action parameters

.changeset/fifty-walls-deny.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/v4/__snapshots__/unboundAction.test.ts.snap, packages/fe-mockserver-core/test/unit/v4/services/unboundAction/EntityContainer.js, packages/fe-mockserver-core/test/unit/v4/services/unboundAction/service.cds, packages/fe-mockserver-core/test/unit/v4/unboundAction.test.ts
There was a bit of mix up with the sticky use case where we do leverage this for standard behavior in an unclean way i guess.
=> fix: Unbound action are now corretly forwarded to custom handlers

.changeset/eleven-seals-explain.md, packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, pnpm-lock.yaml, pnpm-workspace.yaml, samples/basicUsage/CHANGELOG.md, samples/basicUsage/README.md, samples/basicUsage/package.json, samples/basicUsage/ui5.yaml, samples/basicUsage/webapp/Component.js, samples/basicUsage/webapp/annotations/annotation.xml, samples/basicUsage/webapp/index.html, samples/basicUsage/webapp/localService/metadata.xml, samples/basicUsage/webapp/manifest.json
When activating the draft, we need to clean up the DraftAdministrativeData otherwise the object might consider there is still a draft to show
#212
=> fix: remove draft administrative data when activating

.changeset/few-papayas-watch.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/formSample/FormTemplate.cds
The evaluation of draft related properties seemed to have had a flaw in it that was only visible for 1..1 navigation.
Now fixed with this changed, should help #221
=> fix: 1 to 1 navigation was not respecting draft status

.changeset/ninety-pens-jog.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/unboundAction.test.ts
The refactoring of the action introduced a regression during the standard flow (since we always check for action execution before entity interaction...)
=> fix: singleton properties can now be queried individually

.changeset/curvy-seahorses-film.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/data/__snapshots__/functionBasedMockData.test.ts.snap, packages/fe-mockserver-core/test/unit/data/functionBasedMockData.test.ts, packages/fe-mockserver-core/test/unit/data/mockdata/MyRootEntity.js
Fixes #236 
When throwing an error from the mockdata API we were not sending the content-type, which resulted in the error being ignored in the frontend code.
=> Content type error

.changeset/calm-dolls-lay.md, packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts
Fix #238 
So far we didn't take the query parameter into account during draftActivate (like we did for draftEdit)
=> fix: draft Activate will now properly respect passed query parameters

.changeset/healthy-crews-behave.md, packages/fe-mockserver-core/src/router/serviceRouter.ts, packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap, packages/fe-mockserver-core/test/unit/__testData/Requestor.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.js, packages/fe-mockserver-core/test/unit/__testData/RootElement.json, packages/fe-mockserver-core/test/unit/__testData/tenant-003/RootElement.json, packages/fe-mockserver-core/test/unit/middleware.test.ts
This makes for a nicer and simpler usage than with the tenant-xxx in the url as this is handled natively by ui5 and passed down to the proper channels.
=> feat: Allow usage of sap-client as tenantId

.changeset/khaki-poems-confess.md, packages/fe-mockserver-core/package.json, packages/fe-mockserver-core/src/router/serviceRouter.ts, packages/fe-mockserver-core/test/unit/middleware.test.ts
The CSRF token will be issued for a GET or HEAD
request to the service document.
The token will not be validated by the mock server.
Reason: Some client libraries expect the token to
be issued when requested
=> feat(mockserver): Add feature CSRF token

.changeset/thick-dots-travel.md, packages/fe-mockserver-core/src/data/metadata.ts, packages/fe-mockserver-core/test/unit/data/metadata.spec.ts, packages/fe-mockserver-core/test/unit/data/metadata/resolveDraftRoot/MultiDraft.cds, packages/fe-mockserver-core/test/unit/data/metadata/resolveDraftRoot/MultiDraftLinked.cds, packages/fe-mockserver-core/test/unit/data/metadata/resolveDraftRoot/SingleDraft.cds
The draft root resolution sometimes failed when there were multiple draft roots in one service. For example, if two such draft sub-trees were linked by an navigation property.
=> fix(fe-mockserver-core): endless recursion on services with multiple draft roots

.changeset/tidy-crabs-work.md, packages/fe-mockserver-core/src/data/dataAccess.ts
Currently this was done only by entity type which could lead to some unwanted behavior
=> fix: resolve the back navigation using partner first and then by entitytype

.changeset/rotten-trees-lie.md, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
If one of the property identifier started with `or` or `and` the filter parser was unhappy
=> fix: an issue with the filter parser has been fixed

.changeset/lucky-olives-jump.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/actions-and-functions-overload.cds, packages/annotation-converter/test/fixtures/v4/actions-and-functions-overload.xml
The annotation converter only resolved bound actions of the annotation target (@UI.DataFieldForAction on entity A --> only consider actions bound to entity A). With this change it also resolves actions bound to other entity types if they are referenced by `<action FQN>(<other entity FQN>)`.
=> fix(@sap-ux/annotation-converter): resolve @UI.DataFieldForAction.Action if it uses a fully-qualified bound action reference

.changeset/moody-badgers-jump.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
When the filter contained a hashbang character the parsing was cut short and created issue in the filter parser.
This is now fixed
=> fix: Fixed an issue with the filter containing a # character

.changeset/pink-cougars-end.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/request/__snapshots__/odataRequest.test.ts.snap, packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts, packages/fe-mockserver-core/test/unit/v4/__snapshots__/dataAccess.test.ts.snap, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/$filter-tests/AssociatedEntities1.json, packages/fe-mockserver-core/test/unit/v4/services/$filter-tests/AssociatedEntities2.json, packages/fe-mockserver-core/test/unit/v4/services/$filter-tests/Entities.json, packages/fe-mockserver-core/test/unit/v4/services/$filter-tests/service.cds
This PR fixes a limitation on `$filter` expressions. In order to properly apply the filter condition, all data must be available at the time the filter is evaluated. This was only the case when the client requested that data by a corresponding `$expand` parameter.
That is,
`/Entities?$filter=navigationProperty2/value eq 0` and
`/Entities?$filter=navigationProperty2/value eq 0&$expand=navigationProperty2`
probably resulted in a different number of entries.
The mockserver now makes sure that the required data is available to the filters.
=> fix(@sap-ux/fe-mockserver-core): implicitly expand navigation properties used in a filter expression

.changeset/early-icons-change.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/action-enablement.cds, packages/annotation-converter/test/fixtures/v4/action-enablement.xml
Unbound actions usually appear in the list of annotations with empty parentheses at the end, e.g. `UnboundAction()`
=> fix: the annotation converter now resolves annotations of unbound actions

.changeset/fast-bananas-shave.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/complexTypeAnnos.xml
The converter assumed that all properties belong to an EntityType. It now considers ComplexTypes, too.
=> fix(@sap-ux/annotation-converter): Resolve annotations on properties of complex types

.changeset/two-elephants-watch.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts
Previously resolution stopped at the last valid segment of the path
=> fix(@sap-ux/annotation-converter): Correctly return an undefined target when resolving an invalid path

.changeset/empty-gifts-stare.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/v4Meta.xml
Currently if we don't provide a path we would end up with the current entity type which breaks the assumption that a navigationPropertyPath returns a navigation property
=> fix: empty navigation path should lead to an undefined target

.changeset/kind-clocks-sort.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap, packages/fe-mockserver-core/test/unit/__testData/Requestor.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.js, packages/fe-mockserver-core/test/unit/__testData/service.cds, packages/fe-mockserver-core/test/unit/middleware.test.ts
Actions do not need to return anything, but the `MockDataContributor` API did not allow to return `undefined` as an action result. If this was still done, the HTTP response contained the OData context stuff, but it should be a plain 204 No Content response instead.
=> fix(@sap-ux/fe-mockserver-core): Support actions that do not return a value

.github/workflows/codeql-analysis.yml, .github/workflows/pipeline.yml
=> chore: Update Github actions

.changeset/unlucky-eels-sing.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/src/utils.ts, packages/vocabularies-types/utils/config.json, packages/vocabularies-types/utils/generate_types.ts
The vocabulary types now export a list of references to all the vocabularies (in constant `VocabularyReferences`). This ensures that the annotation converter works on a up-to-date list of references.
This also solves the problem of missing `Hierarchy` vocabulary in the `defaultReferences` constant.
=> feat(@sap-ux/vocabularies-types): Generate a collection of vocabulary references

packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/fixtures/v4/aliased.xml
The service-local alias was actually incorrectly defined in the test data (no impact on test results). Also fixes a small typo in a private member.
No changeset required.
=> fix(@sap-ux/annotation-converter): typo and wrong local alias

.changeset/fifty-gorillas-relate.md, .changeset/silver-rings-play.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/src/utils.ts, packages/annotation-converter/test/fixtures/v4/aliased.xml, packages/annotation-converter/test/utils.spec.ts, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/fixtures/v4/aliased.xml, packages/edmx-parser/test/parser.spec.ts, packages/fe-mockserver-core/src/data/metadata.ts, pnpm-lock.yaml
With this PR, the annotation converter can unalias strings even if it encounters an unknown alias. It will assume the alias to stand for the raw metadata namespace, then.
The PR consists of two parts:
- Do not add the schema aliases to the list of references. This brings the output more in line with what the UI5 metamodel returns and helps with unit testing the annotation converter.
- Unalias the annotation targets
The annotation converter now looks at possibly aliased strings as follows. Assume there is a string `alias.foo/not.an.alias.bar(alias.baz)/@vocalias.term`
It will then look at each segment separately:
1. `alias.foo`: `alias` could be an alias because there is only one `.` in this segment. If `alias` is a known reference, replace it with the reference namespace, otherwise …
=> fix: use the namespace as a fallback when unaliasing

.changeset/spotty-bees-unite.md, packages/fe-mockserver-core/src/data/metadata.ts, packages/fe-mockserver-core/test/unit/data/metadata.spec.ts
The existing algorithm was making many assumption that life was easy.
This is a bit more robust (but not enough tested probably).
@c-kobo feel free to add more test case if you feel it's required
=> fix: we now have better support for finding parent of entities

.changeset/dry-guests-matter.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
Fix for #520 #519 
This change technically covers three things
- support for parsing `desc` in the queries
- actually try to support the orderby in the queries (so far ignored)
- making sure that the leaf status is properly set in all case
=> fix: improve hierarchy queries related to sorting

.changeset/heavy-vans-appear.md, packages/annotation-converter/src/writeback.ts, packages/annotation-converter/test/writeback.spec.ts
With this PR, strict checking the value of Boolean type value is removed.
Reason: 
Resolving the type of the value is not possible at the time of applying it as value wouldn't be known at the time.(wrt. Guided Development)
Having a placeholder in place would help replacing it in the later point in time.
With this change it is now possible to apply annotation like so.
```xml
<PropertyValue Property="SearchSupported" Bool="{{searchSupported}}" />
```
=> fix(converter): removed strict checking for a boolean value

.changeset/itchy-dryers-compare.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/v2/__snapshots__/dataAccess.test.ts.snap
This was reported from an internal incident and is also target by #535
=> fix: we now send the correct http header for $count queries

.changeset/sour-roses-prove.md, packages/fe-mockserver-core/src/request/applyParser.ts, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
Fix for the second error reported in #541 
Basically the `max` operator was always matched in `maxAmount` which was breaking some patterns there
=> fix: better analytical queries

.changeset/three-cougars-brake.md, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
Internal Incident where filter
`'EventDateTimeFrom eq 2023-05-02T08:00:00.0000000+08:00 and EventDateTimeTo eq 2023-05-03T07:59:59.0000000+08:00'` results in parser failure
=> fix: fractional second support in the filters

.changeset/gentle-rivers-doubt.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/invalidReferences.xml, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/vocabularies-types/src/Edm.ts
The vocabulary types now allow `undefined` as values for the `$target` property of types `PropertyPath`, `NavigationPropertyPath`, `AnnotationPath` and `PathAnnotationExpression`.
This required adjustments to the annotation converter and mockserver implementations. The annotation converter output now better adheres to the defined types.
Fixes #589
=> fix: $target can be undefined

.changeset/fuzzy-bikes-push.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v2/metadataWithApply.xml, packages/annotation-converter/test/fixtures/v4/metamodelEnums.xml, packages/edmx-parser/src/utils.ts, packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap
The converter now always returns the fixed `VocabularyReferences`.
Fixes #593
=> fix: return the right references

.changeset/afraid-days-roll.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/src/utils.ts, packages/annotation-converter/src/writeback.ts, packages/annotation-converter/test/__snapshots__/converterTest.spec.ts.snap, packages/annotation-converter/test/__snapshots__/writeback.spec.ts.snap, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/utils.spec.ts, packages/annotation-converter/test/writeback.spec.ts
Unaliasing took place only when accessing the AnnotationPath `$target`, but the AnnotationPath `value` still contained the original alias (which is unresolvable for consumers after the conversion, unless the raw data happens to use the "standard" aliases).
Also, when merging annotations from different sources, aliases for annotation targets was not taken into account.
=> fix(@sap-ux/annotation-converter): unalias AnnotationPaths and annotation targets

packages/annotation-converter/src/converter.ts, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/__snapshots__/merge.spec.ts.snap, packages/vocabularies-types/src/Edm.ts
The combination of edmx-parser and annotation-converter resulted in a duplicate resolution of NavigationPropertyBindings: The parser did it on raw metadata level, and the converter then only took the target's fully-qualified name to look up the target again.
This can be simplified by parsing the bindings into fully-qualified names only, and then do the linking during conversion.
=> resolve NavigationPropertyBindings in the converter only

.changeset/quiet-cougars-sit.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/action-parameters.xml, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/fixtures/v4/action-parameters.xml, packages/edmx-parser/test/parser.spec.ts, packages/vocabularies-types/src/Edm.ts
This should now resolve annotations on action (and function) parameters, also for unbound ones.
Action parameter annotations are uniquely resolved since an action is either uniquely bound to an entity type or the single unbound action of the specified name.
This might be different for functions because they can be overloaded not only with respect to their bound entity type, but to all parameters, which could make resolution ambiguous. The first matching function is used in this case.
=> fix: annotations on parameters of unbound actions

.github/workflows/lockfiles-command.yml, .github/workflows/pipeline.yml, package.json, pnpm-lock.yaml
Update of builds to use node version 16. Improvements for `pnpm`.
- set `engines.pnpm` to version `8` in `package.json`
- as `pnpm@8` requires node 16, I've changed the min node version to 16.
- enable [`corepack`](https://github.com/nodejs/corepack) for developers that use multiple package managers
- use latest version ~~`pnpm@8.5.1`~~ `pnpm@8.6.0` for pipeline runs with GitHub actions
- updated the `pnpm-lock.yaml` using `pnpm install` in root with version  ~~`pnpm@8.5.1`~~ `pnpm@8.6.0`
=> chore: min node 16, update pnpm, enable corepack

.changeset/tasty-pigs-shop.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/request/odataRequest.test.ts
`key='abc'` was parsed to `{ key: "'abc'" }`, preserving the apostrophes. Now they are stripped from the string, resulting in `{ key: "abc" }`.
There is no further conversion applied: All value remain strings (as before). That is, `key=123` will result in `{ key: "123" }`.
Fixes #540
=> fix: remove leading and trailing apostrophes from string keys

.github/workflows/lockfiles-command.yml, .github/workflows/pipeline.yml
The GitHub action `pnpm/action-setup@{version}` does not need a version property, if a `packageManager` field in `package.json` is present, see also https://github.com/pnpm/action-setup#version.
This PR removes all `version` fields for `pnpm/action-setup`. This allows to control the version of `pnpm` solely in one place:
https://github.com/SAP/open-ux-odata/blob/3efa8cda8fb0614049eb7ac43db0850ab78d0777/package.json#L52
=> chore: remove version from pnpm/action-setup to use packageManager

.changeset/seven-books-jump.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.json, packages/fe-mockserver-core/test/unit/middleware.test.ts
Fix for #633 
Resolving the path from the entity type also grabbed things that were not actions :)
=> fix: navigation properties will no longer be called as actions

.changeset/rude-pugs-taste.md, packages/annotation-converter/test/converterTest.spec.ts, packages/vocabularies-types/src/Edm.ts, packages/vocabularies-types/utils/generate_types.ts
Only a list pre-curated will be.
This came from the realization that we have too many case where we downcast them as static value instead of thinking about the case.
By reducing the case where this is needed we should have a bit more clarity / control over what is supposed to be dynamic.
This list is maybe not 100% complete as i'm basing it against sap.fe code where there might still be some `any` type around...
=> feat: Annotation values are no longer dynamic by default

.changeset/lemon-bears-pretend.md, packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/__testData/Requestor.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.js, packages/fe-mockserver-core/test/unit/__testData/RootElement.json, packages/fe-mockserver-core/test/unit/middleware.test.ts
Odata request can be sent with Prefer:handling=strict which should fail in case user manual approval is required (412 status code).
Up until now we couldn't evaluate this
=> feat: strict mode is now properly evaluated on the request

.changeset/tough-otters-confess.md, .prettierignore, packages/fe-mockserver-plugin-cds/package.json, packages/fe-mockserver-plugin-cds/test/index.spec.ts, pnpm-lock.yaml
⚠️ The 4.x version of the CDS compiler dropped support for Node.js 14.
=> chore(@sap-ux/fe-mockserver-plugin-cds): Update to @sap/cds-compiler@4

.changeset/eighty-pugs-trade.md, packages/vocabularies-types/utils/generate_types.ts
UI.CreateHidden can be used dynamically (pointing to the parent or to a singleton), for evaluation in StandardAction.ts, this has to be supported by generates type
=> Allow dynamic expression for UI.CreateHidden annotation

.changeset/clean-owls-check.md, packages/fe-mockserver-core/src/request/applyParser.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
I cannot guarantee it will work but the request won't fail outright
=> fix: ancestors queries can parse sub items

.changeset/strange-onions-wash.md, packages/vocabularies-types/utils/generate_types.ts
Inside the Communication vocabulary, lots of types are dynamic and should be dealt as `PropertyAnnotationValue<Edm.String>`instead of `Edm.String`. This change is taking care of updating the Communication.contact and its used types to reflect that binding on those annotations is allowed.
=> fix: update dynamic types list for Communication vocabulary

packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/request/filterParser.test.ts
=> fix: filterParser should allow property name starting with logical operator

packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
When no Levels is specified, it means we should expand all nodes
=> 'Levels' parameter can be omitted in the TopLevels custom function

packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/__testData/Requestor.ts, packages/fe-mockserver-core/test/unit/middleware.test.ts
If it does, the client will preserve it in follow-up requests, resulting in errors
=> fix: 'discard' must not return a `sap-contextid` header

.changeset/early-scissors-listen.md, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/test/unit/data/entitySet.test.ts
If a lambda query contains a method call, the operation fails with a string replace error
=> fix: lambda queries containing method are properly evaluated

.changeset/lucky-planets-own.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/test/unit/v2/dataAccess.test.ts
Internal issue
V2 doesn't support an official $search in the URI, but it seems the standard implementation from the ABAP gateway support a search parameter
=> feat: support the "unofficial" search for v2

.changeset/funny-crabs-guess.md, packages/fe-mockserver-core/src/request/applyParser.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
Fix for internal issue.
Currently we only supported simple keys $root/XXX(xxx) but we can alos have complex keys $root/XXX(xx=ee,ff=rr)
=> fix: hierarchical queries can now support complex keys

.changeset/blue-eggs-try.md, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts, packages/vocabularies-types/utils/config.json, pnpm-lock.yaml
In case simple identifier included a null in their name, they were considered as literals instead which broke some parsing logic
=> fix: we now allow null in literal definition

.changeset/brave-pens-drum.md, packages/vocabularies-types/src/Edm.ts
Currently partner is required, while it's not guaranteed to exist
=> fix: slight change to the vocabulary type for partner navigation

.changeset/lazy-carrots-decide.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/request/applyParser.ts, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
The TopLevels function supports a new parameter 'ExpandLevels', that allows to expand sub-nodes individually
=> feat: support the ExpandLevels parameters in a hierarchical query

.changeset/gorgeous-crabs-decide.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/request/applyParser.ts, packages/fe-mockserver-core/src/request/commonTokens.ts, packages/fe-mockserver-core/src/request/filterParser.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts
The previous implementation was using single quotes, e.g. ExpandLevels=[{'NodeID':'US','Levels':1}]
instead of:
ExpandLevels=[{"NodeID":"US","Levels":1}]
=> fix: ExpandLevel parameters uses double quotes

.changeset/heavy-countries-build.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts
`resolveTarget()` might be called with an (unbound) action FQN missing the trailing `()` that should be there to denote the unbound overload. This is kind of an edge case, though - there can be only one unbound action with a given name in the schema.
=> fix: resolve unbound actions

.changeset/orange-cougars-roll.md, packages/fe-mockserver-core/src/data/common.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyDraftAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/draftService.cds
When displaying a hierarchy for a draft-enabled entity, we only show active instances in the ListReport. Therefore, we add the filter 'IsActiveEntity = true' in the hierarchical query, to ignore draft instances
=> fix: display hierarchy of active instances

.changeset/funny-bears-promise.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyDraftAccess.test.ts
Discarding a draft in a hierarchical service throws an exception
=> fix: discard a draft in a hierarchy

.changeset/calm-ties-taste.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/draftService.cds, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/service.cds
The property names in RecursiveHierarchyType have changed. We support both versions.
=> feat: Support the new version of the com.sap.vocabularies.Hierarchy

.changeset/plenty-experts-try.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyDraftAccess.test.ts
After creating a draft for an existing node, getting the hierarchy with expanded subnodes was returning the nodes in a wrong order.
=> fix: Correct hierarchy with expanded sub-nodes after draft creation

.changeset/twenty-numbers-yawn.md, packages/fe-mockserver-core/src/api.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/ui5-middleware-fe-mockserver/src/configResolver.ts
Some expand / join calls were too slow for my taste.
I've introduced a simple stupid index based approach to speed things up
=> fix: add some index to speed up the resolution of expands

.changeset/four-experts-approve.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
the parseInt messed up the hierarchy calculations
=> fix: hierarchy issue with integer nodes

.changeset/brave-lizards-battle.md, packages/fe-mockserver-core/src/api.ts, packages/fe-mockserver-core/src/data/common.ts, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/src/router/batchRouter.ts, packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap, packages/fe-mockserver-core/test/unit/middleware.test.ts, packages/fe-mockserver-core/test/unit/v4/__snapshots__/unboundAction.test.ts.snap, packages/ui5-middleware-fe-mockserver/src/configResolver.ts
Introduced a new service configuration settings `validateETag` that should force a 412 error when an update doesn't contain the proper If-Match value
=> feat: introduce a basic support for etags

.changeset/flat-mangos-learn.md, packages/fe-mockserver-core/src/router/batchRouter.ts, packages/fe-mockserver-core/test/unit/middleware.test.ts
In case of 412 warnings for changeset request with strict handling, only a single error response needs to be returned with error details per context as part of the error details array. (override any other response if any)
To comply with models requirements to retrigger the selected contexts on confirmation by user
- remove changeset boundary 
- remove content-id in the inner HTTP response, include @Core.ContentId property in the error details only
=> fix: update batchResponse in case of 412 warnings for changeset

.changeset/happy-colts-fail.md, docs/MockserverAPI.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/src/data/entitySets/stickyEntitySet.ts, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/src/mockdata/functionBasedMockData.ts, packages/fe-mockserver-core/test/unit/data/entitySet.test.ts, packages/fe-mockserver-core/test/unit/data/fileBasedMockData.spec.ts, packages/fe-mockserver-core/test/unit/data/functionBasedMockData.test.ts, packages/fe-mockserver-core/test/unit/v4/services/formSample/Countries.js, packages/fe-mockserver-core/test/unit/v4/services/formSample/Countries3.js, packages/fe-mockserver-core/test/unit/v4/services/formSample/Countries4.js
This change also adds an `onAfterRead` extension method to modify the result of the request with additional code.
The change to async for `fetchEntries` and `getAllEntries` is technically a breaking change, but both method were not (and are still not) documented publicly.
=> feat: make the fetchEntries / getAllEntries / onAfterRead method asynchronous

.changeset/long-countries-learn.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/hierarchyDraftAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/Nodes.json, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/Organizations.json, packages/fe-mockserver-core/test/unit/v4/services/hierarchy/otherDraftService.cds
Replaces https://github.com/SAP/open-ux-odata/pull/867
When doing a context.expand(MAX_SAFE_INTEGER), we should expand the node selected and all descendants.
This is done by returning all the children of the node, the type of node, the distance from root and the number of children a node has.
This has been checked on a working backend.
=> Adding tests to support Expand all children of a node 

.changeset/six-swans-end.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/src/router/batchRouter.ts, packages/fe-mockserver-core/test/unit/__snapshots__/middleware.test.ts.snap, packages/fe-mockserver-core/test/unit/__testData/RootElement.js, packages/fe-mockserver-core/test/unit/__testData/service.cds, packages/fe-mockserver-core/test/unit/middleware.test.ts
1. When a change set request fails due to an error in processing one of it's parts, we exit the scenario and don't execute the remaining parts of the change set.
2. We correct the behaviour to return a single error on change set failure.
3. The function handlePart is refactored into:
- ChangeSet case: `getChangeSetResponse`
`    getPartRequest`
`    get412ErrorInfo*`
`    getPartResponse`
`    getCombined412ErrorResponse`
- Isolated case:
`getPartRequest`
`getPartResponse`
4. We add @Core.Content-ID to error response content on change set failures.
5. Due updating service.cds(for adding tests), there seems to a change to etags in existing response snapshots.
6. From changeset error response, removed change set boundary where it was not needed and removed odata-version tag as it is already …
=> fix: provide right response when there are failures in multi select changeset mode

.changeset/nine-pianos-grow.md, packages/fe-mockserver-core/src/request/odataRequest.ts, packages/fe-mockserver-core/src/router/batchRouter.ts, packages/fe-mockserver-core/test/unit/__testData/RootElement.js, packages/fe-mockserver-core/test/unit/middleware.test.ts
We previously added content Id to root error object on changeset failure.
We now add content Ids to error details as well.
=> fix: We add ContentID to error details on changeset failure

.changeset/swift-ants-think.md, package.json, packages/fe-mockserver-core/package.json, packages/fe-mockserver-core/src/middleware.ts, packages/fe-mockserver-core/src/router/catalogServiceRouter.ts, packages/fe-mockserver-core/src/router/serviceRouter.ts, packages/fe-mockserver-core/test/unit/__testData/Requestor.ts, packages/fe-mockserver-core/test/unit/middleware.test.ts, pnpm-lock.yaml, samples/basic-usage/package.json, samples/error-handling/package.json, samples/function-import/package.json
For security reason we can't use the old one anymore. This shouldn't change anything but the matching regexp are a bit more strict than they were before (especially around double / in front)
=> feat: update to router 2.0.0

.changeset/quiet-suits-cough.md, packages/annotation-converter/src/converter.ts, packages/annotation-converter/test/converterTest.spec.ts, packages/annotation-converter/test/fixtures/v4/actions/annotations.xml, packages/annotation-converter/test/fixtures/v4/actions/metadata.xml
When the action FQDN was defined on top of a Collection of items, the way we resolved the unspecific anntotation definition was incorrect and was missing some annotations
=> fix: we now properly support annotations on parameter overload

packages/ui5-middleware-fe-mockserver/README.md
The `sap-client` option is always active and we don't see a reason to disable it, so the contextBasedIsolation only make sense for URL base tenants (which is an old / probably not used anymore feature)
=> Slight reword on the tenant readme

.changeset/fuzzy-rocks-change.md, packages/fe-mockserver-core/src/data/entitySets/entitySet.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/formSample/Countries.json
Current code expect all strings have values
=> fix: support odata filter with tolower or toupper when mockdata contains null

.changeset/angry-berries-cheer.md, .changeset/many-lemons-cheat.md, packages/annotation-converter/src/writeback.ts, packages/annotation-converter/test/__snapshots__/writeback.spec.ts.snap, packages/edmx-parser/src/parser.ts, packages/edmx-parser/src/utils.ts, packages/edmx-parser/test/__snapshots__/parser.spec.ts.snap, packages/vocabularies-types/src/BaseEdm.ts
Types for collection string values did not match the implementation. Type definitions use `StringExpression`, but in parser and wrtieback implementation plain string values were used.
=> fix: type mismatch

.changeset/chilled-starfishes-teach.md, packages/fe-mockserver-core/src/middleware.ts, packages/fe-mockserver-core/test/unit/middleware.test.ts
Services exposed using RAP can include elements in an ABAP namespace, such as `/DMO/UI_TRAVEL_D_D`. Such a pattern results in service paths with `/` replaced by `*` (`/DMO/UI_TRAVEL_D_D` &rarr; `*dmo*ui_travel_d_d`). This causes issues when mocking such a RAP service without manually adjusting URLs.
The router package (or rather "path-to-regexp") treats asterisks as special elements in the path pattern, which causes route setup to fail.
This change works around this issue by only registering the unencoded path if it can be done successfully, and otherwise only using the encoded version (`%2Admo%2Aui_travel_d_d` in this example). As clients usually call the encoded version, this should still work.
=> fix(mockserver): service paths with asterisks

.changeset/gentle-cherries-exist.md, packages/fe-mockserver-core/src/data/dataAccess.ts
In V2, there should be an entityset behind everything navigation, as such we can try and resolve it :()
=> fix: properly identify entityset for parametrized queries

.changeset/neat-forks-beg.md, packages/fe-mockserver-core/src/data/entitySets/draftEntitySet.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/formSample/FormTemplate.cds
Currently, the logic for activate has a tendency to discard part of the draft when the object and the relationship becomes a bit too complicated.
=> fix: we now properly deal with draft in case of complex cross navigation

.changeset/brave-rules-compete.md, packages/annotation-converter/test/converterTest.spec.ts, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/fixtures/v4/action-parameters_4.01.xml, packages/edmx-parser/test/parser.spec.ts
handle odata v4 minor versions - 
fix "Unsupported EDMX version:" message which blocks using a service using odata 4.01 in the fiori generator.
=> handle odata v4 minor versions - fix "Unsupported EDMX version:" message 

.changeset/long-wombats-smile.md, packages/fe-mockserver-core/src/data/dataAccess.ts, packages/fe-mockserver-core/test/unit/v4/dataAccess.test.ts, packages/fe-mockserver-core/test/unit/v4/services/formSample/FormRoot.json
The current code was applying some modification of the data even in case clone operation were not performed.
This resulted in loss of data under some conditions
=> fix: We no longer corrupt the data of embedded navigation properties

.changeset/strange-wasps-shout.md, packages/edmx-parser/src/parser.ts, packages/edmx-parser/test/__snapshots__/parser.spec.ts.snap, packages/edmx-parser/test/fixtures/v4/sdMeta.xml, packages/edmx-parser/test/parser.spec.ts
=> fix: maxLength can have the value `max` which we currently interpret as NaN

.changeset/violet-pans-fry.md, packages/fe-mockserver-core/src/data/serviceRegistry.ts
Registering a new service didn't register the middleware
=> fix: calling loadServices should also open the service to be called back

.changeset/thirty-monkeys-attend.md, packages/fe-mockserver-core/src/mockdata/fileBasedMockData.ts
minor adjustment to https://github.com/SAP/open-ux-odata/pull/949, considering nullable date values
=> fix: date support for v2 - account for nullable dates as well
